telegram.bot.name=job4j_boost_mood_my_bot
telegram.bot.token=8639146647:AAG88aUiOXTjNjMAFgX2bkGRS5uTxAA9ekA
spring.config.location=optional:file:./dev/config/*/
spring.datasource.url=jdbc:h2:file:./moodbot
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
