app.name=job4j_boost_mood_my_bot
app.version=1.0.0
app.url=https://t.me/job4j_boost_mood_my_bot
app.timeout=500
spring.profiles.active=real
remind.period=86400000
recommendation.alert.period=86400000
